refactor: :recycle: Refatorado o gerador do projeto flutter
AgtecPalmas/AgtecCore pull request #29
Opened 2023-08-10 18:25 UTC by guilhermecarvalhocarneiro

Refatorados os arquivos de geração do projeto Flutter separando em arquivos com responsabilidade única.

2023-08-10 21:07 UTC, ThigSchuch commented on {{cookiecutter.project_slug}}/core/management/commands/flutter.py
> +from core.management.commands.flutter_managers.build_add_packages import AddPackagesBuilder
Essas importações não ficariam melhores utilizando o __init__.py?
Seguindo o padrão do Django Managers e FastAPI Managers.

Assim em vez de usar:
```
from core.management.commands.flutter_managers.build_auth_app import AuthAppBuilder
from core.management.commands.flutter_managers.build_controller import ControllerBuilder
```
Será usado assim:
`from core.management.commands.flutter_managers import AuthAppBuilder, ControllerBuilder
`

2023-08-10 21:10 UTC, ThigSchuch requested changes

2023-08-10 21:10 UTC, ThigSchuch commented on {{cookiecutter.project_slug}}/core/management/commands/flutter.py
> +            self._init_flutter()
Será que ficaria melhor, antes do início do projeto poderia checar se o Flutter está instalado, para evitar erros?

2023-08-10 23:20 UTC, guilhermecarvalhocarneiro commented on {{cookiecutter.project_slug}}/core/management/commands/flutter.py
> +from core.management.commands.flutter_managers.build_add_packages import AddPackagesBuilder
Sim fica muito melhor

2023-08-11 18:46 UTC, ThigSchuch approved these changes

2023-08-11 19:02 UTC, tbblack approved these changes

2023-08-11 19:02 UTC, marciohr9 approved these changes

2023-08-11 19:03 UTC, merged