Docs/issue93 add alembic
AgtecPalmas/AgtecCore pull request #94
Opened 2024-02-23 16:43 UTC by ana-flav

Adicionando informações do pacote Alembic na documentação

2024-02-26 16:54 UTC, ronzani commented on {{cookiecutter.project_slug}}/docs/fastapi/alembic.md
> +    Para que o alembic consiga
Acredito que faltou finalizar o texto

2024-02-26 17:01 UTC, ronzani requested changes

2024-02-26 17:01 UTC, ronzani commented on {{cookiecutter.project_slug}}/docs/fastapi/alembic.md
> +    for model in models:
Acho interessante incluir a inicialização do array models e explicar o seu conteúdo.

2024-02-26 17:06 UTC, ronzani requested changes

2024-02-26 17:06 UTC, ronzani commented on {{cookiecutter.project_slug}}/docs/fastapi/alembic.md
> +    Para que o alembic consiga
Acredito que faltou finalizar o texto que explica a necessidade do passo 2

2024-03-07 17:44 UTC, ThigSchuch approved these changes

2024-03-07 18:41 UTC, merged